<%#
 Copyright 2013-2025 the original author or authors from the JHipster project.

 This file is part of the JHipster project, see https://www.jhipster.tech/
 for more information.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-%>
import { vitest } from 'vitest';
import { type Ref, ref } from 'vue';
import { shallowMount, type ComponentMountingOptions } from '@vue/test-utils';
import { type RouteLocation } from 'vue-router';
import { createTestingPinia } from '@pinia/testing';

import { useLogin } from '@/account/login';

import Error from './error.vue';

type ErrorComponentType = InstanceType<typeof Error>;

let route: Partial<RouteLocation>;

vitest.mock('vue-router', () => ({
  useRoute: () => route,
}));

const customErrorMsg = 'An error occurred.';

describe('Error component', () => {
  let error: ErrorComponentType;
  let login: ReturnType<typeof useLogin>;
  let authenticated: Ref<boolean>;
  let mountOptions: ComponentMountingOptions<ErrorComponentType>;

  beforeEach(() => {
    route = {};
    authenticated = ref(false);
    mountOptions = {
      global: {
        plugins: [createTestingPinia()],
        provide: {
          authenticated,
        },
      },
    };
  });

  it('should have retrieve custom error on routing', () => {
    route = {
      path: '/custom-error',
      name: 'CustomMessage',
      meta: { errorMessage: customErrorMsg },
    };
    const wrapper = shallowMount(Error, mountOptions);
    error = wrapper.vm;
    login = useLogin();

    expect(error.errorMessage).toBe(customErrorMsg);
    expect(error.error403).toBeFalsy();
    expect(error.error404).toBeFalsy();
<%_ if (!authenticationTypeOauth2) { _%>
    expect(login.showLogin).toHaveBeenCalledTimes(0);
<%_ } else { _%>
    expect(login.login).toHaveBeenCalledTimes(0);
<%_ } _%>
  });

  it('should have set forbidden error on routing', () => {
    route = {
      meta: { error403: true },
    };
    const wrapper = shallowMount(Error, mountOptions);
    error = wrapper.vm;
    login = useLogin();

    expect(error.errorMessage).toBeNull();
    expect(error.error403).toBeTruthy();
    expect(error.error404).toBeFalsy();
<%_ if (!authenticationTypeOauth2) { _%>
    expect(login.showLogin).toHaveBeenCalled();
<%_ } else { _%>
    expect(login.login).toHaveBeenCalled();
<%_ } _%>
  });

  it('should have set not found error on routing', () => {
    route = {
      meta: { error404: true },
    };
    const wrapper = shallowMount(Error, mountOptions);
    error = wrapper.vm;
    login = useLogin();

    expect(error.errorMessage).toBeNull();
    expect(error.error403).toBeFalsy();
    expect(error.error404).toBeTruthy();
<%_ if (!authenticationTypeOauth2) { _%>
    expect(login.showLogin).toHaveBeenCalledTimes(0);
<%_ } else { _%>
    expect(login.login).toHaveBeenCalledTimes(0);
<%_ } _%>
  });

  it('should have set default on no error', () => {
    const wrapper = shallowMount(Error, mountOptions);
    error = wrapper.vm;
    login = useLogin();

    expect(error.errorMessage).toBeNull();
    expect(error.error403).toBeFalsy();
    expect(error.error404).toBeFalsy();
<%_ if (!authenticationTypeOauth2) { _%>
    expect(login.showLogin).toHaveBeenCalledTimes(0);
<%_ } else { _%>
    expect(login.login).toHaveBeenCalledTimes(0);
<%_ } _%>
  });
});
